In [9]:
import numpy as np
import pandas as pd
from data_outlier import OutlierCapper

# Initialise the transformer with standard 1.5 IQR factor
capper = OutlierCapper(factor = 1.5)

In [10]:
# Standard list with upper (100) and lower (-50) outliers
sample_with_outliers = [10, 12, 11, 13, 12, 11, 14, 12, 100, -50]

In [11]:
# Multi-column DataFrame with extreme outliers in 'age' and 'income'
sample_df = pd.DataFrame({
    "age": [25, 28, 30, 29, 27, 140, 26],         # 140 is an age outlier
    "income": [50000, 52000, 48000, 51000, 49000, 53000, 1500000] # 1,500,000 is an income outlier
})

In [12]:
# Convert 1D list into a 2D DataFrame for OutlierCapper
df_outliers = pd.DataFrame({"original_value": sample_with_outliers})

In [13]:
# Apply OutlierCapper
df_capped = capper.fit_transform(df_outliers)

In [14]:
# Combine into a single visual comparison table
comparison_1d = pd.DataFrame({
    "Original": df_outliers["original_value"],
    "Capped": df_capped["original_value"]
})

In [16]:
print("=== 1D Outlier Capping Visual Output ===")
display(comparison_1d)

=== 1D Outlier Capping Visual Output ===

   Original  Capped
0        10  10.000
1        12  12.000
2        11  11.000
3        13  13.000
4        12  12.000
5        11  11.000
6        14  14.000
7        12  12.000
8       100  15.375
9       -50   8.375

In [17]:
# Apply OutlierCapper across numeric columns
capped_df = capper.fit_transform(sample_df)

In [18]:
print("=== Original DataFrame ===")
display(sample_df)

=== Original DataFrame ===

   age   income
0   25    50000
1   28    52000
2   30    48000
3   29    51000
4   27    49000
5  140    53000
6   26  1500000

In [19]:
print("\n=== Capped DataFrame (Outliers Trimmed to IQR Bounds) ===")
display(capped_df)

=== Capped DataFrame (Outliers Trimmed to IQR Bounds) ===

   age  income
0   25   50000
1   28   52000
2   30   48000
3   29   51000
4   27   49000
5   34   53000
6   26   57000

In [20]:
# Replaces test_data_outliers.py assertions directly inside the notebook
test_df = pd.DataFrame({"value": [1, 2, 3, 4, 100]})
transformed_test = capper.fit_transform(test_df)

In [21]:
# Visual check & Assertion
max_val = transformed_test["value"].max()
assert max_val < 100, f"Assertion Failed: Max value is {max_val}"

In [22]:
print("Test Passed: Outliers successfully capped!")
print(f"Original Max: {test_df['value'].max()} --> Capped Max: {max_val}")

Test Passed: Outliers successfully capped!
Original Max: 100 --> Capped Max: 7